### ISSUE TITLE
In 2.0 b1, nms.getNMSClassInstance sometime would not work well

### ISSUE THREAD

**Issue by zMCdarc** [PluginWiki/Bython#11]
it sometime will throws 

> java.lang.NoSuchMethodException

```
[00:34:14 WARN]: javax.script.ScriptException: java.lang.NoSuchMethodException: java.lang.NoSuchMethodException: net.minecraft.server.v1_9_R2.ChatMessage.<init>(java.lang.String, java.lang.Object) in <script> at line number 1
[00:34:14 WARN]:        at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:202)
[00:34:14 WARN]:        at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:42)
[00:34:14 WARN]:        at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
[00:34:14 WARN]:        at javax.script.AbstractScriptEngine.eval(Unknown Source)
[00:34:14 WARN]:        at pw.mcdarc.mc.bython.EventHooker.hook(EventHooker.java:51)
[00:34:14 WARN]:        at pw.mcdarc.mc.bython.BythonEventListener.PlayerCommandPreprocessEvent(Unknown Source)
[00:34:14 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:34:14 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[00:34:14 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[00:34:14 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[00:34:14 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[00:34:14 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[00:34:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[00:34:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[00:34:14 WARN]:        at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1341)
[00:34:14 WARN]:        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1184)
[00:34:14 WARN]:        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[00:34:14 WARN]:        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[00:34:14 WARN]:        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[00:34:14 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[00:34:14 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[00:34:14 WARN]:        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45)
[00:34:14 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726)
[00:34:14 WARN]:        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)
[00:34:14 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)
[00:34:14 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)
[00:34:14 WARN]:        at java.lang.Thread.run(Unknown Source)
[00:34:14 WARN]: Caused by: Traceback (most recent call last):
  File "<script>", line 1, in <module>
  File "<script>", line 16, in onCommand
  File "<script>", line 16, in onCommand
        at java.lang.Class.getConstructor0(Unknown Source)
        at java.lang.Class.getConstructor(Unknown Source)
        at pw.mcdarc.mc.bython.Util.ReflectionUtil.getConstructor(ReflectionUtil.java:232)
        at pw.mcdarc.mc.bython.Util.ReflectionUtil.invokeConstructor(ReflectionUtil.java:287)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)

java.lang.NoSuchMethodException: java.lang.NoSuchMethodException: net.minecraft.server.v1_9_R2.ChatMessage.<init>(java.lang.String, java.lang.Object)

[00:34:14 WARN]:        at org.python.core.Py.JavaError(Py.java:546)
[00:34:14 WARN]:        at org.python.core.Py.JavaError(Py.java:537)
[00:34:14 WARN]:        at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:188)
[00:34:14 WARN]:        at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
[00:34:14 WARN]:        at org.python.core.PyObject.__call__(PyObject.java:515)
[00:34:14 WARN]:        at org.python.core.PyObject.__call__(PyObject.java:521)
[00:34:14 WARN]:        at org.python.core.PyMethod.__call__(PyMethod.java:171)
[00:34:14 WARN]:        at org.python.pycode._pyx12.onCommand$2(<script>:20)
[00:34:14 WARN]:        at org.python.pycode._pyx12.call_function(<script>)
[00:34:14 WARN]:        at org.python.core.PyTableCode.call(PyTableCode.java:167)
[00:34:14 WARN]:        at org.python.core.PyBaseCode.call(PyBaseCode.java:124)
[00:34:14 WARN]:        at org.python.core.PyFunction.__call__(PyFunction.java:403)
[00:34:14 WARN]:        at org.python.pycode._pyx13.f$0(<script>:1)
[00:34:14 WARN]:        at org.python.pycode._pyx13.call_function(<script>)
[00:34:14 WARN]:        at org.python.core.PyTableCode.call(PyTableCode.java:167)
[00:34:14 WARN]:        at org.python.core.PyCode.call(PyCode.java:18)
[00:34:14 WARN]:        at org.python.core.Py.runCode(Py.java:1386)
[00:34:14 WARN]:        at org.python.core.__builtin__.eval(__builtin__.java:497)
[00:34:14 WARN]:        at org.python.core.__builtin__.eval(__builtin__.java:501)
[00:34:14 WARN]:        at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:259)
[00:34:14 WARN]:        at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:40)
[00:34:14 WARN]:        ... 25 more
[00:34:14 WARN]: Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_9_R2.ChatMessage.<init>(java.lang.String, java.lang.Object)
[00:34:14 WARN]:        at java.lang.Class.getConstructor0(Unknown Source)
[00:34:14 WARN]:        at java.lang.Class.getConstructor(Unknown Source)
[00:34:14 WARN]:        at pw.mcdarc.mc.bython.Util.ReflectionUtil.getConstructor(ReflectionUtil.java:232)
[00:34:14 WARN]:        at pw.mcdarc.mc.bython.Util.ReflectionUtil.invokeConstructor(ReflectionUtil.java:287)
[00:34:14 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:34:14 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[00:34:14 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[00:34:14 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[00:34:14 WARN]:        at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
[00:34:14 WARN]:        ... 43 more```

**Comment by zMCdarc** [comment]
you should notice that i hava input right args......

**Comment by lymenglei** [comment]
`java.lang.NoSuchMethodException`
说的很明显了，应该是你用java调用python的时候，没有找到对应的方法。
检查下方法名字有没有拼写错误或者是其它问题

**Comment by zMCdarc** [comment]
不啊....你能不能看清楚点报错233
报错里面都是显示我反射出来的构造函数不存在....我也不知道为什么.

**Comment by lymenglei** [comment]
妈蛋我好困这一上午，脑袋都是蒙的

**Comment by zMCdarc** [comment]
233333333叫你熬夜23333333
